<?php
$host = "localhost";
$login_db = "root";
$senha_db = "batatapalha";
$db = 'oil_rescue';
$conectar = mysqli_connect($host, $login_db, $senha_db, $db);
$sql = ("SELECT MAX(cd_estado) FROM tb_estados");
$query = mysqli_query($conectar, $sql);
$row = mysqli_fetch_array($query);
$new_id = $row[0];
$new_id++;


$insert = "";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('0', '$insert')";
mysqli_query($conectar, $sql);

$insert = "Acre";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Alagoas";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Amapá";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Amazonas";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Bahia";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Ceará";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Distrito Federal";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Espírito Santo";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Goiás";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Maranhão";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Mato Grosso";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Mato Grosso do Sul";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Minas Gerais";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Pará";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Paraíba";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Paraná";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Pernambuco";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Piauí";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Rio de Janeiro";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Rio Grande do Norte";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Rio Grande do Sul";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Rondônia";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Roraima";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Santa Catarina";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "São Paulo";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Sergipe";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;
$insert = "Tocantins";
$sql = "INSERT INTO tb_estados (cd_estado, nm_estado) VALUE ('$new_id', '$insert')";
mysqli_query($conectar, $sql);
$new_id++;

?>